name: Release

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: 
      - completed

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: python-semantic-release/python-semantic-release@v9.21.0
